name: test and build/package anroid apk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: test cmd
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: pull docker image and package apk
      run: |
        sudo docker pull cangol/android-gradle
        sudo chmod +x src/boat-house-android-proj/gradlew 
        sodu docker run --tty --interactive --volume=$(pwd)/src/boat-house-android-proj:/opt/workspace --workdir=/opt/workspace --rm cangol/android-gradle  /bin/sh -c "./gradlew assembleDebug"

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: boat-house-debug-apk.zip
        # A file, directory or wildcard pattern that describes what to upload
        path: $(pwd)/src/boat-house-android-proj/app/build/outputs/apk
